sudo: false
language: python
# Default Python version is usually 2.7
python: 3.5

# To turn off cached cython files and compiler cache
# set NOCACHE-true
# To delete caches go to https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cache directories will be deleted if anything in ci/ changes in a commit
cache:
 ccache: true
 directories:
  - $HOME/.cache # cython cache
  - $HOME/.ccache # compiler cache

env:
  global:
    # create a github personal access token
    # cd pandas-dev/pandas
    # travis encrypt 'PANDAS_GH_TOKEN=personal_access_token' -r pandas-dev/pandas
    - secure: "EkWLZhbrp/mXJOx38CHjs7BnjXafsqHtwxPQrqWy457VDFWhIY1DMnIR/lOWG+a20Qv52sCsFtiZEmMfUjf0pLGXOqurdxbYBGJ7/ikFLk9yV2rDwiArUlVM9bWFnFxHvdz9zewBH55WurrY4ShZWyV+x2dWjjceWG5VpWeI6sA="

git:
    # for cloning
    depth: 2000

matrix:
    fast_finish: true
    exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5

    include:
    - dist: trusty
      env:
        - JOB="3.7" ENV_FILE="ci/deps/travis-37.yaml" PATTERN="(not slow and not network)"

    - dist: trusty
      env:
        - JOB="2.7" ENV_FILE="ci/deps/travis-27.yaml" PATTERN="(not slow or (single and db))"
      addons:
        apt:
          packages:
          - python-gtk2

    - dist: trusty
      env:
        - JOB="3.6, locale" ENV_FILE="ci/deps/travis-36-locale.yaml" PATTERN="((not slow and not network) or (single and db))" LOCALE_OVERRIDE="zh_CN.UTF-8"

    - dist: trusty
      env:
        - JOB="3.6, coverage" ENV_FILE="ci/deps/travis-36.yaml" PATTERN="((not slow and not network) or (single and db))" PANDAS_TESTING_MODE="deprecate" COVERAGE=true

    # In allow_failures
    - dist: trusty
      env:
        - JOB="3.6, slow" ENV_FILE="ci/deps/travis-36-slow.yaml" PATTERN="slow"

    # In allow_failures
    - dist: trusty
      env:
        - JOB="3.6, doc" ENV_FILE="ci/deps/travis-36-doc.yaml" DOC=true
    allow_failures:
      - dist: trusty
        env:
          - JOB="3.6, slow" ENV_FILE="ci/deps/travis-36-slow.yaml" PATTERN="slow"
      - dist: trusty
        env:
          - JOB="3.6, doc" ENV_FILE="ci/deps/travis-36-doc.yaml" DOC=true

before_install:
  - echo "before_install"
  # set non-blocking IO on travis
  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - source ci/travis_process_gbq_encryption.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - git tag
  # Because travis runs on Google Cloud and has a /etc/boto.cfg,
  # it breaks moto import, see:
  # https://github.com/spulec/moto/issues/1771
  # https://github.com/boto/boto/issues/3741
  # This overrides travis and tells it to look nowhere.
  - export BOTO_CONFIG=/dev/null

install:
  - echo "install start"
  - ci/prep_cython_cache.sh
  - ci/install_travis.sh
  - ci/submit_cython_cache.sh
  - echo "install done"

before_script:
  - ci/install_db_travis.sh
  - export DISPLAY=":99.0"
  - ci/before_script_travis.sh

script:
  - echo "script start"
  - source activate pandas-dev
  - ci/build_docs.sh
  - ci/run_tests.sh

after_script:
  - echo "after_script start"
  - source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
  - if [ -e test-data-single.xml ]; then
        ci/print_skipped.py test-data-single.xml;
    fi
  - if [ -e test-data-multiple.xml ]; then
        ci/print_skipped.py test-data-multiple.xml;
    fi
  - echo "after_script done"
